version: "3"
services:

  spark-master-${instanceId}:
    image: manager.localdomain:5000/spark:2.2.0-test1
    hostname: spark-master-${instanceId}
    command: bin/spark-class org.apache.spark.deploy.master.Master -h spark-master-${instanceId}
    environment:
      TZ: Europe/Brussels
    ports:
      - ${instanceId}081:8080
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 1G

  spark-worker-${instanceId}:
    image: manager.localdomain:5000/spark:2.2.0-test1
    hostname: spark-worker-${instanceId}
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master-${instanceId}:7077
    environment:
      SPARK_WORKER_CORES: 12
      SPARK_WORKER_MEMORY: 20g
      PYTHONPATH: /mnt/data/lib
      TZ: Europe/Brussels
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 20g
        reservations:
          memory: 20g
    volumes:
      - /mnt/data:/mnt/data

  zeppelin-${instanceId}:
    image: manager.localdomain:5000/spark_zeppelin:2.2.0_0.7.3-test1
    hostname: zeppelin-${instanceId}
    ports :
      - "${instanceId}${instanceId}080:8080"
    environment:
      - SPARK_HOME=/opt/spark
      - MASTER=spark://spark-master-${instanceId}:7077
      - ZEPPELIN_JAVA_OPTS=-Dspark.executor.memory=20g
      - ZEPPELIN_NOTEBOOK_DIR=/opt/NotebookRepo
      - HTTP_PROXY=http://proxy.lbs.alcatel-lucent.com:8000
      - HTTPS_PROXY=http://proxy.lbs.alcatel-lucent.com:8000
      - http_proxy=http://proxy.lbs.alcatel-lucent.com:8000
      - https_proxy=http://proxy.lbs.alcatel-lucent.com:8000
      - PYTHONPATH=/mnt/data/lib:/
      - TZ=Europe/Brussels
    command: bin/zeppelin.sh
    volumes:
      - /mnt/data:/mnt/data
      - /mnt/NotebookRepo:/opt/NotebookRepo
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 4G
